language: java

before_script: cd h2

script: ./build.sh jar testFast

cache:
  directories:
    - $HOME/.m2/repository

matrix:
  include:
    - jdk: oraclejdk8 
      dist: trusty
      group: edge
      sudo: required
      addons:
        apt:
          packages:
            - oracle-java8-installer
    - jdk: openjdk7 
      dist: trusty
      group: edge
      sudo: required
      addons:
        apt:
          packages:
            - openjdk-7-jdk